### ISSUE TITLE
Correção de Texto

### ISSUE THREAD

**Issue by natan-rocha** [dirceuresende/checklist_seguranca#13]
https://github.com/dirceuresende/checklist_seguranca/blob/937ea8dfcdde19ac70e5c2160379afd8f00a6407/stpChecklist_Seguranca.sql#L128

".. mas também autenticação SQL Server, utiliando usuário .."

".. mas também autenticação SQL Server, utilizando usuário .."

**Comment by dirceuresende** [comment]
Corrigido!
Obrigado pela sugestão :)
