### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by sm8680** [dirceuresende/checklist_seguranca#16]
The following code will error in SQL Server 2008R2 or versions of SQL Server that don't have the containment and containment_desc column.  Consider using a SQL Server parameter in an if statement to bypass the code from being execute.

DECLARE @SQLVersion AS tinyint -- Stores the SQL Server Version Number(8(2000),9(2005),10(2008 & 2008R2),11(2012),12(2014),13(2016),14(2017),15(2019))
SET @SQLVersion = (@@microsoftversion / 0x1000000) & 0xff

IF @SQLVersion > 10
        SELECT 
			name AS 'Contained/@name',
			containment AS 'Contained/@containment', 
			containment_desc AS 'Contained/@contaiment_type', 
			is_auto_close_on AS 'Contained/@auto_close'
		FROM 
			sys.databases
		WHERE 
			containment <> 0 
			AND is_auto_close_on <> 0
		FOR XML PATH(''), ROOT('Configuracao_AC_Habilitado'), TYPE

**Comment by sm8680** [comment]
--Added code 

    ---------------------------------------------------------------------------------------------------------------
    -- Verify 'AUTO_CLOSE' is set to 'OFF' on contained 
    ---------------------------------------------------------------------------------------------------------------

IF @SQLVersion > 10
   BEGIN

    SET @Resultado = NULL

-- Below code is commented for it breaks in SQL Server 2008

/*    SET @Resultado = (
        SELECT 
			name AS 'Contained/@name',
			containment AS 'Contained/@containment', 
			containment_desc AS 'Contained/@contaiment_type', 
			is_auto_close_on AS 'Contained/@auto_close'
		FROM 
			sys.databases
		WHERE 
			containment <> 0 
			AND is_auto_close_on <> 0
		FOR XML PATH(''), ROOT('Configuracao_AC_Habilitado'), TYPE
    )
*/

DECLARE @sqlCommand NVARCHAR(4000)

set @sqlCommand = N'set @Resultado = (SELECT 
			name AS ''Contained/@name'',
			containment AS ''Contained/@containment'', 
			containment_desc AS ''Contained/@contaiment_type'', 
			is_auto_close_on AS ''Contained/@auto_close''
		FROM 
			sys.databases
		WHERE 
			containment <> 0 
			AND is_auto_close_on <> 0
		FOR XML PATH(''''), ROOT(''Configuracao_AC_Habilitado''), TYPE)'
execute sp_executesql @sqlCommand, N'@Resultado XML OUTPUT', @Resultado OUTPUT

    IF (@language = 'pt')
    BEGIN
        
        UPDATE #Resultado
        SET 
            Ds_Resultado = (CASE WHEN @Resultado IS NULL THEN 'OK' ELSE 'Possível problema encontrado' END),
            Ds_Detalhes = @Resultado
        WHERE 
            Id_Verificacao = 18

    END
    ELSE IF (@language = 'en')
    BEGIN

        UPDATE #Resultado
        SET 
            Ds_Resultado = (CASE WHEN @Resultado IS NULL THEN 'OK' ELSE 'Possible issue found' END),
            Ds_Detalhes = REPLACE(CAST(@Resultado AS VARCHAR(MAX)), 'Configuracao_AC_Habilitado>', 'Contained_AC_Enabled>')
        WHERE 
            Id_Verificacao = 18
        
    END
	END

**Comment by dirceuresende** [comment]
Nice! I'll fix this with your suggestion!

Thanks
