### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by lennybacon** [dirceuresende/checklist_seguranca#2]
In the [blog post](https://www.dirceuresende.com/blog/stpsecurity_checklist-best-practices-and-security-checklist-for-sql-server/) you wrote that you translated the SPROC in many hours to english. The messages all seem to be Brasilia Portuguese. Did you commit the wrong file?

**Comment by Gerrit-Grote** [comment]
Scroll down a little bit until: 
"ELSE IF (@language = 'en')" 
There you'll find the english messages
