### ISSUE TITLE
SQL 2014

### ISSUE THREAD

**Issue by lennybacon** [dirceuresende/checklist_seguranca#3]
In SQL 2014 the following error is thrown:

```
Msg 156, Level 15, State 1, Line 14
Incorrect syntax near the keyword 'OR'.
Msg 111, Level 15, State 1, Line 19
'CREATE/ALTER PROCEDURE' must be the first statement in a query batch.
```

The Syntax `CREATE OR ALTER PROCEDURE` is not supported.

An improvement would be a **minimal requirement**  in the read me or  a version check in the script itself.

**Comment by dirceuresende** [comment]
Hi Lenny!
Thanks for your tip. I fixed this issue by removing CREATE OR ALTER PROCEDURE and leaving only ALTER PROCEDURE (I create before, if it doesn't exists)

**Comment by lennybacon** [comment]
(Y)
